<a href="https://colab.research.google.com/github/2303a51732santhosh/2303A51732_Python_for_Datascience/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

marks = np.array([
    [78, 85, 90],
    [92, 88, 76],
    [67, 73, 70],
    [89, 94, 91],
    [56, 60, 65]
])

print("Original Marks Array:\n", marks)

print("\nAverage marks of each student:", np.mean(marks, axis=1))
print("Minimum marks of each student:", np.min(marks, axis=1))
print("Maximum marks of each student:", np.max(marks, axis=1))

print("\nMarks of 3rd student (index 2):", marks[2])
print("\nStudents with any subject > 80:\n", marks[np.any(marks > 80, axis=1)])

subject_wise = marks.T
print("\nSubject-wise Marks (Transposed):\n", subject_wise)

print("Average marks per subject:", np.mean(subject_wise, axis=1))

data = {
    'Student': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'Math': marks[:, 0],
    'Physics': marks[:, 1],
    'Chemistry': marks[:, 2]
}

df = pd.DataFrame(data)
print("\nOriginal DataFrame:\n", df)

df['Average'] = df[['Math', 'Physics', 'Chemistry']].mean(axis=1)
df['Passed'] = df['Average'] >= 80

print("\nDataFrame with 'Average' and 'Passed' columns:\n", df)

high_scorers = df[df['Average'] > 80]
print("\nStudents with Average > 80:\n", high_scorers)

overall_avg = df[['Math', 'Physics', 'Chemistry']].mean()
print("\nSubject-wise Overall Averages:\n", overall_avg)


Original Marks Array:
 [[78 85 90]
 [92 88 76]
 [67 73 70]
 [89 94 91]
 [56 60 65]]

Average marks of each student: [84.33333333 85.33333333 70.         91.33333333 60.33333333]
Minimum marks of each student: [78 76 67 89 56]
Maximum marks of each student: [90 92 73 94 65]

Marks of 3rd student (index 2): [67 73 70]

Students with any subject > 80:
 [[78 85 90]
 [92 88 76]
 [89 94 91]]

Subject-wise Marks (Transposed):
 [[78 92 67 89 56]
 [85 88 73 94 60]
 [90 76 70 91 65]]
Average marks per subject: [76.4 80.  78.4]

Original DataFrame:
   Student  Math  Physics  Chemistry
0      S1    78       85         90
1      S2    92       88         76
2      S3    67       73         70
3      S4    89       94         91
4      S5    56       60         65

DataFrame with 'Average' and 'Passed' columns:
   Student  Math  Physics  Chemistry    Average  Passed
0      S1    78       85         90  84.333333    True
1      S2    92       88         76  85.333333    True
2      S3    67       73 

In [2]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT'],
    'Salary': [55000, 48000, 72000, 60000, 51000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

filtered_df = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", filtered_df)

sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nDataFrame Sorted by Salary (Descending):\n", sorted_df)

df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus Column:\n", df)

df['Total_Compensation'] = df['Salary'] + df['Bonus']
print("\nDataFrame with Total Compensation:\n", df)

total_expense = df['Total_Compensation'].sum()
print("\nTotal Salary Expense including Bonuses:", total_expense)

df.to_csv('employee_salary_analysis.csv', index=False)


Original DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   55000
1      Bob  102         IT   48000
2  Charlie  103    Finance   72000
3    David  104  Marketing   60000
4      Eve  105         IT   51000

Employees with Salary > 50,000:
       Name   ID Department  Salary
0    Alice  101         HR   55000
2  Charlie  103    Finance   72000
3    David  104  Marketing   60000
4      Eve  105         IT   51000

DataFrame Sorted by Salary (Descending):
       Name   ID Department  Salary
2  Charlie  103    Finance   72000
3    David  104  Marketing   60000
0    Alice  101         HR   55000
4      Eve  105         IT   51000
1      Bob  102         IT   48000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   55000  5500.0
1      Bob  102         IT   48000  4800.0
2  Charlie  103    Finance   72000  7200.0
3    David  104  Marketing   60000  6000.0
4      Eve  105         IT   51000  5100.0

DataFrame with To